[9610] wlbt: Change function name from __ieee80211_get_channel to ieee80211_get_channel (Android P)
Fixes following compilation errors. Looks like it is simple case of function name change in api

drivers/net/wireless/scsc/mgt.c: In function 'slsi_select_wifi_sharing_ap_channel':
drivers/net/wireless/scsc/mgt.c:4033:4: error: implicit declaration of function '__ieee80211_get_channel' [-Werror=implicit-function-declaration]
    settings->chandef.chan = __ieee80211_get_channel(wiphy, settings->chandef.chan->center_freq);
    ^
drivers/net/wireless/scsc/mgt.c:4033:27: warning: assignment makes pointer from integer without a cast
    settings->chandef.chan = __ieee80211_get_channel(wiphy, settings->chandef.chan->center_freq);
                           ^
drivers/net/wireless/scsc/mgt.c:4038:28: warning: assignment makes pointer from integer without a cast
     settings->chandef.chan = __ieee80211_get_channel(wiphy, sta_frequency);
                            ^
drivers/net/wireless/scsc/mgt.c:4062:29: warning: assignment makes pointer from integer without a cast
      settings->chandef.chan = __ieee80211_get_channel(wiphy, sta_frequency);
                             ^
drivers/net/wireless/scsc/mgt.c:4066:28: warning: assignment makes pointer from integer without a cast
     settings->chandef.chan = __ieee80211_get_channel(wiphy, SLSI_2G_CHANNEL_ONE);

Change-Id: Ia1d3792d014495f6a09a53d3569d84b75d0a9575
SCSC-Bug-Id: SSB-40175
Signed-off-by: Tarun Karela <t.karela@samsung.com>